### ISSUE TITLE
Email signatures for Thunderbird

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#19]
Since the majority of us emails through Thunderbird we need to have a unified email signature when we communicate between us and with third parties. Please @AnXh3L0 proceed with a proposal for a signature, a small guide for adding the signature and also don't forget to use open source fonts :)
I think Giannis had worked on this, but I can not remember details about it. 

Deadline: 11.12.2017.

**Comment by AnXh3L0** [comment]
Hi Redon,

The email signatures have been created before and are in the [Ura cloud](https://cloud.ura.design/s/1njE1OwvwSUYg0W). You can download them there and use them in your Thunderbird account.

In order to add them, follow [this tutorial](https://www.mail-signatures.com/articles/how-to-set-up-email-signature-in-thunderbird/).

**Comment by AnXh3L0** [comment]
Please report here when you have added them to your Thunderbird.

**Comment by rskikuli** [comment]
Done on my side.

**Comment by AnXh3L0** [comment]
Any update from others? I consider this issue closed because the files are already in the cloud and we can set them up quickly (others that haven't responded yet, please confirm your actions in the group chat).
