### ISSUE TITLE
Introduce Identihub at Open Labs

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#28]
Please introduce Identihub at Open Labs community (forum) in order to propose to make is as the default platform that presents the Open Labs visual ID. 

Deadline: 25.12.2017.

**Comment by elioqoshi** [comment]
Again, as said in the other thread regarding the launch, I think it's still too early to use Identihub for standard usage when it's barely Alpha yet. We are just starting out with Dev work and there is a great list of features and bugs which need yet to be fixed. From a sysadmin perspective it's also not safe to switch platforms to an official channel. Open Labs branding is currently on GitHub here: https://github.com/OpenLabsHackerspace/branding

Once Identihub is presentable, has docs which actually work and don't suck, have the features we planned for the launch and is installable on your own server without being a sysadmin god, we could present it. I'd prefer to take our time on this and do it right rather than rush ourselves on it.

**Comment by rskikuli** [comment]
Closing this based on comments.

**Comment by elioqoshi** [comment]
My comments didn't mean this should be closed. It meant that it was not ready. You wouldn't want to open another issue later on. There are a few bugs which should get wrapped up in April and I think it should be good to showcase.

**Comment by elioqoshi** [comment]
It would be good to catch up with this after a few more features are added. @marianaballa @rskikuli shall we propose an event in the next 4 weeks?

**Comment by rskikuli** [comment]
This could be a nice follow up to the Open Source Design workshop - part 2. Thoughts?

**Comment by marianaballa** [comment]
Both ideas work for me. I mean, we can combine them. 
When it comes to an "OSD" - related workshop, @AnXh3L0 and @elioqoshi are those who should tell us whether we should announce an event like this or not. 

I checked OL's wiki and there is only one event planed for the upcoming weeks ("Angular workshop" on July 3rd).

**Comment by marianaballa** [comment]
Regarding this one, we have scheduled an event at Open Labs for July 14th. Renata will also be present. 

Open Labs forum post: https://forum.openlabs.cc/t/identihub-workshop/1229

**Comment by rskikuli** [comment]
Cool I'll talk to our photographer to document it. Please arrange a moment for group photo @marianaballa .

**Comment by kominoshja** [comment]
One thing we can do is have a "Release Party" once our first stable release is out. Let me know what you think

**Comment by elioqoshi** [comment]
This is done already. Also closing since Identihub is separate from Ura now.
