### ISSUE TITLE
Identihub website: newsletter registration

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#35]
When registering for newsletter it is not clear if:

- you registered (thank you message);
- you have already registered;
- you are entering a wrong email format. In this case it also shows an 'error format' message, but also that you have successfully registered to the database (test it and check please).
Software used: Firefox Quantum, Ubuntu version. 

Deadline: 17.01.2018

**Comment by AnXh3L0** [comment]
The first point of your issue has been solved, meanwhile the second one (if a user has already registered) can't be solved based on our current form because the POST method we use just sends the submitted emails to a list and doesn't have the ability to check for already existing emails and show messages.

The third point has been partially fixed (the Submit  button is now disabled and you can't submit empty emails, also the email textbox shows a red border when your email doesn't have the correct format) mostly because it is a limitation of the platform (no php can be implemented on GH pages).

**Comment by AnXh3L0** [comment]
I am dealing with implementing the form from scratch using PHP, for that I would need a database in the backend to check for existing emails/add new ones and display messages according to the situation. ping @Borisbudini can we do that with TinyLetter? Does it have an API we can use to call for form submissions?

**Comment by AnXh3L0** [comment]
The new subscription form has been implemented in the website and does everything we needed. Closing this issue.
