### ISSUE TITLE
Promotional material design for Identihub

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#36]
Following the growing presence of the team in different conferences we need to have some tools that communicate and promote Identihub better. Here is a list of materials needed to be designed (or edited from actual designs) especially now that Fosdem 2018 is close:

- stickers;
- business cards (generic) - should include Patreon campaign support as well;
- Identihub 3D printed material (maybe post at thingyverse as well?);
- other promo materials for events and conferences (branded balloons, tshirts etc) 

Please proceed first with proposals (here) before finalizing the materials. @elioqoshi ideas about printing specs welcome. 

All the above should be published in a Github repo:

- in a preview format;
- with the source file for easy editing in the future - open source format;
- ready to be sent for printing;

Deadline: 12.01.2018.

**Comment by rskikuli** [comment]
@AnXh3L0 @elioqoshi are the materials we have so far documented?

**Comment by elioqoshi** [comment]
We ordered a few things and should be good to go for now. Also let's make sure tasks like these have actual deliverables and are not open-ended. Otherwise it's hard to estimate when an issue can be considered finished. Also, let;s break up tasks into smaller pieces so they can be picked up quicker (so instead of "Promotional Items for Identihub", let's say "3D Printed Items for Identihub presence at FrOSCon 2018"

Closing this since we are progressing with swag and we can open other issues when needed.
