### ISSUE TITLE
Revamp Ura website

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#4]
Design and development of the new www.ura.design website. This will include the following processes:

- brainstorming process; 
- design of the landing page;
- design of the internal pages;
- technical implementation.

As agreed during our work week, the website should reflect the creative and innovative character of Ura crew.

This should be ready to be presented before our presence at FOSDEM 2017.

**Comment by rskikuli** [comment]
Seems like this will not be ready before February. New deadline: 1.03.2018.

**Comment by elioqoshi** [comment]
As discussed, this will be needed to be pushed even further down the road. so 8 March would be a good date.

@AnXh3L0 can you do a quick status update?

**Comment by AnXh3L0** [comment]
Sure! At the moment I am importing the latest blogposts from the old website and creating the portfolio pages with our best works so far.

**Comment by rskikuli** [comment]
Comments based on the latest update: 

> Ura is the digital studio which focuses on visual communication solutions tailored for Open Source and Internet Freedom projects. Ura was founded in 2016 in Albania to cater to the ever-rising demand for Usability and Design services in Open Source Software. Among others, we are specialized in UX Design, Design Systems Research and Visual Identity.
> Our work can be seen across various Open Source projects such as Mozilla. The Tor Project and The Linux Foundation. **(link to the projects with an efect on mouse over)**
> We also develop Identihub, Open Source Software to self-host visual assets and identities to ease collaboration between designers and developers.
> 

- what can we do to improve the search engine optimization features of the website? 
- homepage: 'our team' needs to be 'CORE TEAM'
- 'OUR TEAM' can we have a mouse over on each photo of the team members?
- homepage: featured projects need a background or something that generates a nice composition (ask me about this if needed).
- https://ura.design/jobs/: There are no open positions at the moment.
Subtext: We are a growing every day and are always in need for new talent in the areas of UX Design, Design Systems Research, Visual Identity and web development. When we have open positions we tend to prioritize Identihub **(link)** contributors and Open Source Design **(link)** contributors. 
For all applicants we apply Equal Opportunity Employer Policies (link to https://pad.ura.design/p/equalopportunityemployerpolicy). @elioqoshi will confirm this. 
- https://ura.design/services: use another image that has not been used in the website. The one we have now is used in the homepage;
- https://ura.design/projects/ **(more projects - this is important)**;
- Logobridge: triple check that the links at the logos are working. We need to measure the number of clicks on this. Maybe a service like bit.ly? https://ura.design/logobridge;
- https://ura.design/supporters: remove UNDP;

**Comment by AnXh3L0** [comment]
> Ura is the digital studio which focuses on visual communication solutions tailored for Open Source and Internet Freedom projects. Ura was founded in 2016 in Albania to cater to the ever-rising demand for Usability and Design services in Open Source Software. Among others, we are specialized in UX Design, Design Systems Research and Visual Identity.
Our work can be seen across various Open Source projects such as Mozilla. The Tor Project and The Linux Foundation. (link to the projects with an efect on mouse over)
We also develop Identihub, Open Source Software to self-host visual assets and identities to ease collaboration between designers and developers.

Done

> what can we do to improve the search engine optimization features of the website?

There's not much but I'll make sure to improve the discoverability and make it more compatible with search engines.

> homepage: 'our team' needs to be 'CORE TEAM'

Changed

> 'OUR TEAM' can we have a mouse over on each photo of the team members?

What mouseover do you want here?

> homepage: featured projects need a background or something that generates a nice composition (ask me about this if needed).

I think it could get more polished but we can't create a "general" background feel because these are not subprojects of Ura but works done by us.

> https://ura.design/jobs/: There are no open positions at the moment.
Subtext: We are a growing every day and are always in need for new talent in the areas of UX Design, Design Systems Research, Visual Identity and web development. When we have open positions we tend to prioritize Identihub (link) contributors and Open Source Design (link) contributors.
For all applicants we apply Equal Opportunity Employer Policies (link to https://pad.ura.design/p/equalopportunityemployerpolicy). @elioqoshi will confirm this.

I have added the subtext but not the Equal Opportunity Employeer Policies yet, will wait for confirmation from Elio for the text to create the subpage for it.

> https://ura.design/services: use another image that has not been used in the website. The one we have now is used in the homepage;

This is under way at the moment of writing.

> https://ura.design/projects/ (more projects - this is important);

This will be implemented soon after some further polishing of the website.

> Logobridge: triple check that the links at the logos are working. We need to measure the number of clicks on this. Maybe a service like bit.ly? https://ura.design/logobridge;

The links there are correct because I re-did them from scratch when creating this subpage; I think Nextcloud must have a way to count downloads on a specific file, not sure if we want to go with services such as bit.ly (yourls which is open source but we need our own domain for that to work out). Needs opinions.

> https://ura.design/supporters: remove UNDP;

Removed.

**Comment by elioqoshi** [comment]
Not sure how much sense an open door policy makes in an EEO when everyone is remote and there is no office. In any case, the document looks good to me.

@Borisbudini @AnXh3L0 can't Matomo measure the clicks on Logobridge?

**Comment by kominoshja** [comment]
I will get back to you about this tomorrow!

**Comment by AnXh3L0** [comment]
The new website has been implemented with all the changes requested - if there's nothing left we can close this.

**Comment by rskikuli** [comment]
@elioqoshi Open Door Policy used to be literally what the term means. With the rise of remote work it is still used as a term referring to the limited barrier between a decision maker and other people in an organization. So if you want that to be part of the culture it might be a good thing to state it to people that approach your company.  
Anyway, closing this because the requested changes have been made. if new updates are required let's open a new issue. Again, great job everyone involved!
