### ISSUE TITLE
Open Source Design workshop in Tirana

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#46]
Organization of the first open source design workshop and meetup in Tirana. 
Logistics (including promo): @marianaballa & @redon
Presentations & workshop hosting: @elioqoshi & @AnXh3L0
Detailed brief to follow. 

Event date: 17.02.2018
Event poster: 31.01.2018
Outreach: 7.02.2018

**Comment by rskikuli** [comment]
We need to open up the registrations for this @Borisbudini . Free seats and with optional donations, same approach with CopyFest event organized at the hackerspace. Deadline: 9.02.2017.

**Comment by kominoshja** [comment]
As discussed in the chat the task was transferred to @marianaballa. Reflecting that here

**Comment by marianaballa** [comment]
Registrations opened for the workshop before deadline. I posted it at Open Labs's[ forum.](https://forum.openlabs.cc/t/open-source-design-workshop/939)

**Comment by rskikuli** [comment]
Will make sure we have photos. @marianaballa follow up blog post needed.

**Comment by elioqoshi** [comment]
Event done. The were issues with the event time so we ended up doing 2 workshops.
Andis was there and took photos:

Post mortem:

Contra
- Let's double check the time and date of the events on all channels as this has slipped away it seems
- Let's not use registrations next time. It might discourage some people from coming. Maybe not allowing anymore people in after x number of people entered, might be a good solution. To be honest, having 5 people there and teaching them was hard enough really. I don't think it's doable for more than 10 people for Anxhelo and me properly. 
- We lost time installing and downloading software at the beginning. This can be avoided by putting them on flash drives and installing the software beforehand on the Open Labs laptops.
- We were unable to install and launch Inkscape on a Macbook (but not really much we could do)

Pro
- Anxhelo and me were well in sync in explaining according to a participant. Especially the 2nd workshop went smooth since we did the first one.
- The environment was chill and relaxed I think. I did some stupid jokes to break the ice which I hope didn't cross a line. (is this a con maybe?)
- There was a lot of interest in Open Labs, generally open source and Ura at the event, so people didn't just come and go for the event.
- The workflow of the different tools we explained went really well. Also the practical part of designing a poster for a well known brand was also pretty interesting as it was not only theory anymore.

-----------------------

Follow up tasks ( @marianaballa )
- add participants emails to newsletter
- request photos from Andis/ required editing/ upload them on our Nextcloud
- write short blog post / report of the workshop
- cross post on Patreon
- add section to Newsletter (very short, link to blog post)
- share on channels (Open Source Design Forum etc)

**Comment by AnXh3L0** [comment]
@rskikuli the event and followup are completed, let's close this?
