### ISSUE TITLE
Patreon updates for January 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#47]
Preparation for update of our Patreons. Main points of: 

- main activity: change of Patreon account from Ura to Identihub (reasons);
- latest news from our blog (CCC);
- upcoming events (Fosdem)

Deadline for content proposal: 18.01.2018
Update for send out: 22.01.2018

**Comment by elioqoshi** [comment]
I should have posted regarding the change to Identihub so that should be fine.

@marianaballa I'd suggest posting a short update that we will be at FOSDEM, have a OSD booth, have an OSD talk as well. Also mention that Redon will be giving a talk too.

This should be fine as a Patreon post without posting on our blog I guess.

**Comment by rskikuli** [comment]
There is no post regarding the change to Identihub at Identihub Patreon page https://www.patreon.com/ura/posts. This is sensitive in order to be clear to our actual Patreons. 
My talk will not be related to Identihub so not sure if this should be mentioned.

**Comment by elioqoshi** [comment]
It's in the description. It should be fine I'd say

**Comment by rskikuli** [comment]
This is published https://www.patreon.com/posts/join-us-at-2018-16734784. Closing this.
