### ISSUE TITLE
LibOCon 2018 visual identity

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#79]
Brainstorming, proposals and implementation of the visual ID for Libocon 2018 conference that will happen in Tirana in September 2018. 

Deadline for first ideas: week 29.05.2018
Deadline for final poster proposal: 05.06.2018
Deadline for implementation of the visual ID to all the materials: 12.06.2018

**Comment by elioqoshi** [comment]
@rskikuli we need to brainstorm about this. When is the next LiboCon Meeting?

P.S: The deadlines are absurdly unrealistic.

**Comment by rskikuli** [comment]
We will soon have some pressure from the conference organizing team about this. Please @elioqoshi and @AnXh3L0 an update about the dates of the first drafts.

**Comment by elioqoshi** [comment]
@rskikuli I just asked you yesterday about details first.

**Comment by rskikuli** [comment]
@AnXh3L0 can you please share the visual ID or brand guidelines of LibreOffice (I know we don't have info about LiboCon). This will help Kristi get on board with the project easily. I have only found this one as a visual element related to LibreOffice 6 https://en.wikipedia.org/wiki/File:LibreOffice_6.0.1.1_Start_Center_Screenshot.png. Is there anything else?

**Comment by rskikuli** [comment]
List of deliverables is work on progress here: https://pad.ura.design/p/LibOcon_2018_design_deliverables. Final material will be shared here at this issue. Please add anything that I have missed. Ping @kristicunga.

**Comment by rskikuli** [comment]
What license will the visual materials be @elioqoshi @AnXh3L0 ?

**Comment by rskikuli** [comment]
Follow up from the meeting with @kristicunga: first draft of the design: 03.07.2018.
Kristi, final design of the poster should be: 06.07.2018 because there is no time to print the materials and get approval from the community.

**Comment by AnXh3L0** [comment]
@rskikuli here are the branding guidelines for LibreOffice: https://wiki.documentfoundation.org/Marketing/Branding

**Comment by kristicunga** [comment]
@rskikuli the poster is done till 06.03. See you tomorrow at 16.30 for the first draft presentation. 🙌

**Comment by rskikuli** [comment]
Here are the deliverables for the project:

**Poster text**

- title: LibOcon 2018
- subtitle: The LibreOffice Community yearly conference
- description: The 8th edition of the LibreOffice community featuring presentations, workshops, community meetings and hackfests. 
- when: September 25 to September 28, 2018 
- where: Oficina, Tirana, Albania. 
- website: https://libocon.com
- QR code leading to the OpenStreetMap position of the venue.


**Deliverables**

- Poster [ ]
- Twitter cover [ ]
- Facebook cover [ ] 
- Roll up banners (details needed) [ ]
- tshirts [ ] 
- tote bags [ ] 
- Openlabs.cc slider image [ ] 
- Open Labs newsletter image (600 px wide max) [ ] 
- stickers [ ]
- agenda (printed) [ ] 
- lanyard/badges and (speaker, participant, crew, volunteer) [ ] 

All the materials should have a print file (when applicable) and a preview image (only for print materials).

**Comment by kristicunga** [comment]
For the development of the visual identity of LibOCon 2018, we worked on the poster as the main creative of the conference. Each creative proposal of the poster will focus on some important elements of the event such as:

- the local elements of the city that will host the event;
- LibreOffice branding - by using elements as described at the TDF wiki https://wiki.documentfoundation.org/Marketing/Branding.

After a long discussion, we decided to choose the Tirana clock tower as a distinctive element of the city. The most difficult and interesting part of the whole creative process was finding a balance between those two elements.

### Logo creative concept
Every conference needs also a logo which will be used not only in the main creative (poster) but also to different other elements such as social media creative materials, stickers etc. For this edition of the conference, we sketched a monoline icon of the clock tower of the city, inside a hexagonal frame as the logo. The clock tower is one of the most popular and most recognizable symbols of Tirana. It is a part of old buildings ensemble of the city center, and it belongs to the city since the beginning of the 19th century.
For logotype, we used a slab and open source font as Zilla [bold] al la Aaron Draplin (https://en.wikipedia.org/wiki/Aaron_Draplin) style. We also picked the LibreOffice green and composed it with black and white, to keep it connected with the brand and make it clear. The [template for the] logo is also easily adapted to next conferences: we can change the city, the year below and replace Tirana clock tower with a certain symbol from the next host city of LibOcon.

### Poster creative concept

**Creative direction: stamp tower**
Stamps are always closely connected with a certain place and manifest a big event for that place. They are created for personalities and significant events such as the Olympic Games, the year of literature, the World Cup etc. Using the same symbolism we are using the stamp as an element that shows the significance of the vent for the LibreOffice community. The dates and the venue of the conference are composed in a seal, as they stay for real in postcards. The stamp with the clock tower, the seal of the venue and posters vintage texture make the participants feel like they're a postcard, as a souvenir from Tirana. The green color of the brand guidelines makes the poster easily identifiable for the community.

**Creative direction: cube tower**
For this creative direction, we stayed at the same local element of the city (clock tower), but we tried an evident element from LibreOffice, especially the last version 6.0. The cubes from the LibreOffice 6 screen splashstay behind the clock tower into an isometric perspective. In a contrast with the previous creative direction, this one is more vital by the colors, with some modernist geometrical shapes and a clean background. In this creative direction, the focus is on LibreOffice 6 and the local elements come at a secondary importance.

**Creative direction: lo poster**
_Creative approach description about this poster will be added soon._

### Presentation of the creative ideas
[LibOCon 2018 - Creative Proposals - Ura.pdf](https://github.com/uracreative/task-management/files/2201844/LibOCon.2018.-.Creative.Proposals.-.Ura.pdf)

**Comment by italovignoli** [comment]
I like the logo, while for the poster I am really undecided between the stamp and the cubes. The stamp would be better as a pure poster, but the cubes are more flexible and probably more appropriate for social media.

**Comment by elioqoshi** [comment]
@italovignoli Thanks Italo! All directions have a clear path forward on how to use for different sizes and formats, even the stamp direction so I wouldn't worry about that too much yet :)

**Comment by italovignoli** [comment]
After your explanation and a second look, my preference goes to the stamp.

**Comment by HeikoTietze** [comment]
Being late at the party you may still look for the original artwork of the 6.0 logo which is here https://wiki.documentfoundation.org/Marketing/Branding#LibreOffice_6.0_series

Nice proposals, very professional. Don't have a favorite.

**Comment by rskikuli** [comment]
Based on the feedback from TDF members and from the local LibOcon organizing team comments we are proceeding with the proposed logo and the proposal with the stamp. @kristicunga please proceed with:

- finalization of the poster in a standard printing format and also silkscreen printing technique;
- poster presentation similar to https://mir-s3-cdn-cf.behance.net/project_modules/disp/f8060b10731927.560e9fdad0682.jpg.
- deliver of the logo in different shapes such as horizontal, vertical, with and without background color etc. Published at Identihub?
- social media material (at least for Facebook event cover, Facebook, Twitter header and Instagram)

**Deadline for the above: 26.07.2018.**

**Comment by rskikuli** [comment]
The local organizing team is requesting to move faster with this since we are close to the event. At least the social media material should be ready asap.

**Comment by kristicunga** [comment]
Hello everyone,

Here you can find the social media assets. We are looking forward for your feedback.

![libocon-2018-social-media-assets-facbook-cover-eq](https://user-images.githubusercontent.com/40668901/43577461-2f557886-964c-11e8-8eb0-3f2318e4985b.jpg)
Facebook cover

---
![libocon-2018-social-media-assets-facebook-event-cover-eq](https://user-images.githubusercontent.com/40668901/43577462-2f7c9768-964c-11e8-86c2-af2b1f0e8d5c.jpg)
Facebook event cover

---
![libocon-2018-social-media-assets-twitter-header-eq](https://user-images.githubusercontent.com/40668901/43578126-25c0af46-964e-11e8-89d1-d90b597b7e3b.jpg)
Twitter header

---
![libocon-2018-social-media-assets-instagram-post-eq](https://user-images.githubusercontent.com/40668901/43578145-3230b500-964e-11e8-92be-bb10fed7287f.jpg)
Instagram poster

**Comment by kristicunga** [comment]
Also, we updated the poster: changing the seal from _SEPTEMBER 25 - 28, 2018_ to _2018 EDITION_; and coloring _LIBREOFFICE_ with green.

[LibOCon 2018 - Final Poster.pdf](https://github.com/uracreative/task-management/files/2253058/LibOCon.2018.-.Final.Poster.pdf)

**Comment by rskikuli** [comment]
Thank you @kristicunga . We are starting to share the social media materials starting from today. As next steps please find below a reminder on the required deliverables:

- Poster [X]
- Twitter cover [X]
- Facebook cover [X]
- Facebook event image [X]
- Conference logo [X]
- Roll up banners (details below) [  ]
- tshirts for crew [ ]
- tshirts for participants [ ]
- tote bags [ ]
- Openlabs.cc slider image [ ]
- libocon.org header image (details below) [ ]
- Open Labs newsletter image (600 px wide max) [ ]
- stickers related to the conference [ ]
- agenda in PDF and printed (details will follow late August) [ ]
- lanyard/badges for speaker, participant, crew, volunteer (details will follow) [ ]

**Notes:** 
- All the materials should have a print file (when applicable) and a preview image that shows how these materials look.
- conference logo  needs to be published on different sizes and shapes published @ Identihub;

I would kindly ask you to have the materials the soonest due to the strict deadlines, especially for the printing materials.

**Comment by elioqoshi** [comment]
![libocon 2018 social media assets - v2 elio_twitter header](https://user-images.githubusercontent.com/5436686/43645268-a87f201e-9731-11e8-97e1-de20e6daa620.jpg)

Sorry, we got the Twitter image wrong (their guidelines are quite problematic). This should work better.
Preview:

![image](https://user-images.githubusercontent.com/5436686/43645232-942bc02c-9731-11e8-8463-3c36d9ef0dd8.png)

**Comment by rskikuli** [comment]
@ all: final logo of the conference is published here: https://demo.identihub.co/libocon-2018#/. Please use this one.

**Comment by rskikuli** [comment]
Ura team: any update on the deliverables that are pending? We need send the files asap for printing. Thank you.

**Comment by AnXh3L0** [comment]
@rskikuli the first batch of the assets are now in the [repo](https://github.com/uracreative/works/tree/master/LibOCon%202018). The remaining ones are being added as we speak.

**Comment by AnXh3L0** [comment]
At the moment, these are the deliverables present in the repo.

- Poster [X]
- Twitter cover [X]
- Facebook cover [X]
- Facebook event image [X]
- Conference logo [X]
- Roll up banners [X]
- T-shirts for crew and participants (same logo for both polo and t-shirt) [X]
- Tote bags [X]
- Openlabs.cc slider image [X]
- libocon.org header image [X]
- Open Labs newsletter image [X]
- Stickers related to the conference [X]
- Lanyard/badges for speaker, participant, crew, volunteer [X]

Missing at the moment is:
- Agenda in PDF and printed (details will follow late August) [ ]

**Comment by rskikuli** [comment]
Thanks @AnXh3L0 . Reviewing the material. If there is something I'll get back to you. 
There is a request from TDF about an [Impress](https://www.libreoffice.org/discover/impress/) template that will be used from the speakers of the event. Can you provide this?

**Comment by rskikuli** [comment]
Just reviewed the materials with the local team. It is very important to have a preview of how the materials will look (mockup). This will help us make sure that the printing house understands exactly what we are expecting from them. When can we have this @AnXh3L0 ?

**Comment by rskikuli** [comment]
Reminder about this @AnXh3L0 . Also I can not find the libocon.com header image at the repo where the deliverables are. Can you share it please?

**Comment by AnXh3L0** [comment]
Yes, I will take care of these ASAP. [Here's](https://github.com/uracreative/works/blob/master/LibOCon%202018/Social%20Media/Others/PNG/LibOCon%20Website%20-%20Header.png) the header image you wanted.

**Comment by rskikuli** [comment]
I saw you mockups @AnXh3L0. Looking Good thanks. The printing house will need also an indication of the dimensions and size of the printings. This will ensure that the printings are correct. Can you do that?

**Comment by rskikuli** [comment]
Any news on this @AnXh3L0 ? Guidance of the size of the printing materials is important because the printing house might print the materials in the wrong size. 

There are also some materials related to our sponsors and partners where Ura will also be present. This materials include roll up banner for sponsors, backdrop and poster design. Le
Can you also inform me about the LibreOffice Impress template? Are you going to implement it or we need to find an alternative?

**Comment by AnXh3L0** [comment]
Yes @rskikuli, I will add the print sizes and guidelines in a new folder in the assets repo.
About the other materials, the roll up banners and backdrop, we have to wait a bit more because the sponsors might not be finalized yet. 
I am working on the Impress template and I will send it today in the mailing list for others to use it (both 4:3 and 16:9 formats).

**Comment by rskikuli** [comment]
@AnXh3L0 can we have a better application of the design for openlabs.cc website? 
![image](https://user-images.githubusercontent.com/17770262/44957814-c5d36500-aed6-11e8-8545-617f61cf81db.png)

**Comment by AnXh3L0** [comment]
@rskikuli The new image for the Open Labs website slider is online in the repo.

**Comment by elioqoshi** [comment]
This is finished and documented here: 
https://ura.design/projects/libocon

Thanks to everyone involved!
